function home() {
  const content = document.getElementById('content');
  const top = document.createElement('div');
  const header = document.createElement('header');
  const div1 = document.createElement('div');
  const div2 = document.createElement('div');
  const h1 = document.createElement('h1');
  const p1 = document.createElement('p');
  const p2 = document.createElement('p');
  const p3 = document.createElement('p');
  const p4 = document.createElement('p');
  const p5 = document.createElement('p');
  const tabs = document.createElement('div');
  const tabs__nav = document.createElement('div');
  const tabs__nav_btn = document.createElement('button');
  const tabs__content = document.createElement('div');
  const tabs__item = document.createElement('div');
  const tabs__item_p = document.createElement('p');
  tabs.setAttribute('class', 'tabs');
  tabs__nav.setAttribute('class', 'tabs__nav');
  tabs__nav_btn.setAttribute('class', 'tabs__nav-btn');
  tabs__nav_btn.setAttribute('type', 'button');
  tabs__nav_btn.setAttribute('data-tab', '#tab_1');
  tabs__nav_btn.textContent = 'Home';
  tabs__content.setAttribute('class', 'tabs__content');
  tabs__item.setAttribute('class', 'tabs__item');
  tabs__item.setAttribute('id', 'tab_1');
  top.setAttribute('class', 'top');
  top.setAttribute('id', 'top');
  header.setAttribute('class', 'hero');
  p2.setAttribute('class', 'price');
  p4.setAttribute('class', 'price');
  div1.setAttribute('class', 'cta cta1');
  div2.setAttribute('class', 'cta cta2');

  h1.textContent = "Terry's Taco Joint";
  p1.textContent = 'Pretty Good Tacos!';
  p2.textContent = '$1.99';
  p3.textContent = 'Tacos';
  p4.textContent = '$3.99';
  p5.textContent = 'Kombucha';
  tabs__item_p.textContent =
    "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).";
  content.appendChild(tabs);
  tabs.appendChild(tabs__nav);
  tabs__nav.appendChild(tabs__nav_btn);
  tabs.appendChild(tabs__content);
  tabs__content.appendChild(tabs__item);
  tabs__item.appendChild(tabs__item_p);
  tabs__content.appendChild(top);
  top.appendChild(header);
  top.appendChild(div1);
  top.appendChild(div2);
  header.appendChild(h1);
  header.appendChild(p1);
  div1.appendChild(p2);
  div1.appendChild(p3);
  div2.appendChild(p4);
  div2.appendChild(p5);
}

export default home;
